input_dir="datasets/OpenBioLink-Small/"
base_output_dir="output/OpenBioLink-Small/"
update_confs=0
sg_penalty=0
path_length=3
total_iterations=1000
eval_every=10
patience=2
rule_base_reward=3
only_body=0
embedding_size="64 256"
hidden_size=64
LSTM_layers=2
beta=0.05
Lambda="0.5 1"
learning_rate="0.0001 0.0015"
max_num_actions=150
train_entity_embeddings=1
use_entity_embeddings=1
num_rollouts=50
test_rollouts=100
load_model=0
model_load_path="./models/OpenBioLink-Small/model.ckpt"